import Head from "next/head";
import { useEffect, useState } from "react";

import { Box } from "@chakra-ui/layout";

import { Table } from "../../components/common/Table";
import { Category } from "../../models/Category";

import type { NextPage } from "next";
import { getManyBase } from "../../services/common";
import { categoryResource } from "../../services/category";

const Home: NextPage = () => {
  const [categories, setCategory] = useState<Category[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const categories = await getManyBase<Category>({
        resource: categoryResource,
      });

      setCategory(categories);
    };

    fetchData();
  }, []);

  const columns = ["Nome", "Tema"];

  const tableContent = categories.map((category) => {
    const getContent = (values: string[] | undefined[]) =>
      values.map((value) => (value ? value : "-"));

    return {
      id: category.id as string,
      values: getContent([category.name, category.theme?.name]),
    };
  });

  return (
    <Box>
      <Head>
        <title>Categorias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box role="main" p={"2rem"}>
        <Table
          title="Categorias"
          columns={columns}
          columnsContent={tableContent}
        />
      </Box>
    </Box>
  );
};

export default Home;
