import Head from "next/head";
import { useEffect, useState } from "react";

import { Box } from "@chakra-ui/layout";
import { RequestQueryBuilder } from "@nestjsx/crud-request";

import { Table } from "../../components/common/Table";
import { Category } from "../../models/Category";
import { categoryResource } from "../../services/category";
import { getManyBase } from "../../services/common";
import { formatDate } from "../../utils/date";

import type { NextPage } from "next";
const Home: NextPage = () => {
  const [categories, setCategory] = useState<Category[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const requestQuery = RequestQueryBuilder.create().sortBy({
        field: "createdDate",
        order: "DESC",
      }).queryObject;

      const categories = await getManyBase<Category>({
        resource: categoryResource,
        requestQuery,
      });

      setCategory(categories);
    };

    fetchData();
  }, []);

  const columns = ["Nome", "Tema", "Criado", "Atualizado"];

  const tableContent = categories.map((category) => {
    const getContent = (values: (string | undefined)[]) =>
      values.map((value) => (value ? value : "-"));

    return {
      id: category.id as string,
      values: getContent([
        category.name,
        category.theme?.name,
        formatDate(category.createdDate, { relative: true }),
        formatDate(category.updatedDate, { relative: true }),
      ]),
    };
  });

  return (
    <Box>
      <Head>
        <title>Categorias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box role="main" p={"2rem"}>
        <Table
          title="Categorias"
          columns={columns}
          columnsContent={tableContent}
          uploadEndpoint={`${categoryResource}/importCsv`}
        />
      </Box>
    </Box>
  );
};

export default Home;
