import Head from "next/head";
import { useEffect, useState } from "react";

import { Box } from "@chakra-ui/layout";

import { Table } from "../../components/common/Table";
import { Theme } from "../../models/Theme";

import type { NextPage } from "next";
import { getManyBase } from "../../services/common";
import { themeResource } from "../../services/theme";

const Home: NextPage = () => {
  const [themes, setThemes] = useState<Theme[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const themes = await getManyBase<Theme>({
        resource: themeResource,
      });

      setThemes(themes);
    };

    fetchData();
  }, []);

  const columns = ["Nome"];

  const tableContent = themes.map((theme) => {
    const getContent = (values: string[] | undefined[]) =>
      values.map((value) => (value ? value : "-"));

    return {
      id: theme.id as string,
      values: getContent([theme.name]),
    };
  });

  return (
    <Box>
      <Head>
        <title>Temas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box role="main" p={"2rem"}>
        <Table
          title="Temas"
          resource="theme"
          columns={columns}
          columnsContent={tableContent}
        />
      </Box>
    </Box>
  );
};

export default Home;
