import Head from "next/head";

import { Box } from "@chakra-ui/layout";

import { Table } from "../../components/common/Table";
import hintsModel from "../../models/hints.model";
import { hintResource } from "../../services/hint";

import type { NextPage } from "next";

const Home: NextPage = () => {
  const columns = [
    "author",
    "book",
    "tip",
    "timesDrawn",
    "createdDate",
    "updatedDate",
  ];

  return (
    <Box>
      <Head>
        <title>Sentenças</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box role="main" p={"2rem"}>
        <Table
          model={hintsModel}
          title="Sentenças"
          columns={columns}
          uploadEndpoint={`${hintResource}/importCsv`}
        />
      </Box>
    </Box>
  );
};

export default Home;
